Fix bug in cross-references Improve error handling in the latex2png scripts so that old .png files are not inserted erroneously
git-svn-id: https://latex2rtf.svn.sourceforge.net/svnroot/latex2rtf/trunk@188 e562ef82-0334-0410-8083-dbe22b1e9a75

diff --git a/scripts/latex2png_1 b/scripts/latex2png_1
--- a/scripts/latex2png_1
+++ b/scripts/latex2png_1
@@ -48,9 +48,29 @@ dir=`dirname "$1"`
 #need to search the current working directory for \input or \include
 TEXINPUTS=`pwd`":"
 cd $dir
-latex  --interaction batchmode $name > /dev/null
+rm -f $name.png
+rm -f $name.dvi
+latex  --interaction batchmode $1 > /dev/null
+
+if [ ! -e "$name.dvi" ] ; then
+ 	error "ERROR: latex failed to create $name.dvi from $name.tex"
+	exit 1
+fi
+
 dvips -E -o $name.eps $name.dvi >& /dev/null
+
+if [ ! -e "$name.eps" ] ; then
+ 	error "ERROR: dvips failed to create $name.eps from $name.dvi"
+	exit 1
+fi
+
 convert -crop 0x0 -density ${opt_d}x${opt_d} $name.eps $name.png
+
+if [ ! -e "$name.png" ] ; then
+ 	error "ERROR: ImageMagick convert failed to create $name.png from $name.eps"
+	exit 1
+fi
+
 if [ $opt_k -eq 0 ] ; then
 	rm -f $name.dvi
 	rm -f $name.aux
diff --git a/scripts/latex2png_2 b/scripts/latex2png_2
--- a/scripts/latex2png_2
+++ b/scripts/latex2png_2
@@ -44,8 +44,23 @@ dir=`dirname "$1"`
 #need to search the current working directory for \input or \include
 TEXINPUTS=`pwd`":"
 cd $dir
+rm -f $name.png
+rm -f $name.pdf
+
 pdflatex $name > /dev/null
+
+if [ ! -e "$name.pdf" ] ; then
+ 	error "ERROR: pdflatex failed to create $name.pdf"
+	exit 1
+fi
+
 pstoimg -crop lbtr -density ${opt_d} -type png $name.pdf >& /dev/null
+
+if [ ! -e "$name.png" ] ; then
+ 	error "ERROR: pstoimg failed to create $name.png from $name.pdf"
+	exit 1
+fi
+
 if [ $opt_k -eq 0 ] ; then
 	rm -f $name.aux
 	rm -f $name.log
diff --git a/scripts/latex2png_3 b/scripts/latex2png_3
--- a/scripts/latex2png_3
+++ b/scripts/latex2png_3
@@ -47,11 +47,31 @@ dir=`dirname "$1"`
 #need to search the current working directory for \input or \include
 TEXINPUTS=`pwd`":"
 cd $dir
+rm -f $name.png
+rm -f $name.dvi
+
 latex  --interaction batchmode $name > /dev/null
+
+if [ ! -e "$name.dvi" ] ; then
+ 	error "ERROR: latex failed to create $name.dvi from $name.tex"
+	exit 1
+fi
+
 dvips -E -o $name.eps $name.dvi >& /dev/null
+
+if [ ! -e "$name.eps" ] ; then
+ 	error "ERROR: dvips failed to create $name.eps from $name.dvi"
+	exit 1
+fi
+
 gs -dNOPAUSE -sDEVICE=pbmraw -r${opt_d} -sOutputFile=$name.pbm $name.eps -c quit.ps >& /dev/null
 pnmcrop $name.pbm | pnmtopng > $name.png 2> /dev/null
  
+if [ ! -e "$name.png" ] ; then
+ 	error "ERROR: gs/pnmcrop/pnmtopng failed to create $name.eps from $name.png"
+	exit 1
+fi
+
 if [ $opt_k -eq 0 ] ; then
 	rm -f $name.dvi
 	rm -f $name.aux
diff --git a/scripts/latex2png_4 b/scripts/latex2png_4
--- a/scripts/latex2png_4
+++ b/scripts/latex2png_4
@@ -46,8 +46,23 @@ dir=`dirname "$1"`
 #need to search the current working directory for \input or \include
 TEXINPUTS=`pwd`":"
 cd $dir
+rm -f $name.png
+rm -f $name.pdf
+
 pdflatex --interaction batchmode $name > /dev/null
+
+if [ ! -e "$name.pdf" ] ; then
+ 	error "ERROR: pdflatex failed to create $name.pdf from $name.tex"
+	exit 1
+fi
+
 convert -crop 0x0 -density ${opt_d}x${opt_d} $name.pdf $name.png
+
+if [ ! -e "$name.png" ] ; then
+ 	error "ERROR: ImageMagick convert failed to create $name.png from $name.pdf"
+	exit 1
+fi
+
 if [ $opt_k -eq 0 ] ; then
 	rm -f $name.aux
 	rm -f $name.log
