Add -c -g -m and -i options to all scripts.  Make default, _1 and _2 scripts work with included eps files.  -i support not implemented. latex2png was contributed by B. Horeni, but mangled by me so it probably does not work on any platform at the moment.
Finally, -i support will be added when the inline equation option
is added to the latex2rtf source.


git-svn-id: https://latex2rtf.svn.sourceforge.net/svnroot/latex2rtf/trunk@267 e562ef82-0334-0410-8083-dbe22b1e9a75

diff --git a/scripts/latex2png_1 b/scripts/latex2png_1
--- a/scripts/latex2png_1
+++ b/scripts/latex2png_1
@@ -1,96 +1,115 @@
 #!/bin/sh
+# Part of latex2rtf by Scott Prahl (Nov 2002)
+#
 # This version uses latex and dvips
+#			   with ps2ps (part of Ghostscript)
 #              with convert (Part of ImageMagick)
 #
+
+DVIPS="dvips -E -R"
+LATEX="latex --interaction batchmode"
+CONVERT="convert -crop 0x0"
+PS2PS="ps2ps"
+TEXINPSEP=":"
+
 help()
 {
     cat <<HELP
 latex2png -- convert latex file to PNG image
 
-USAGE: latex2png [-d density] [-h] [-k] [-H home dir] latex_file
+USAGE: latex2png [-d density] [-h] [-k] [-c] [-g] [-m] [-H home dir] latex_file
 
 OPTIONS: 
-         -c             color images
-         -d density 	(where density is in pixels per inch)
-         -g             gray images
-         -i             inline equations with leading dot
-         -h         	this help text
-         -k         	keep intermediate files (for debugging)
-         -H /home/dir	directory to be included in search path
+         -c color image
+         -g gray image  
+         -m monochrome  (default)
 
-EXAMPLE: latex2png -d 144 -H /usr/home /tmp/eqn  (to create /tmp/eqn.png)
+         -d density     (default 144 dpi)
+         -h help        (default '.')
+         -H /home/dir	directory to be included in search path
+         -i             used to locate baseline of equations
+         -k         	keep intermediate files (for debugging)
+
+EXAMPLE: 
+		 latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
+         latex2png -H . /tmp/file     #search the cwd for image files
 
 HELP
     exit 0
 }
 
-LATEX=latex
 opt_d=144
 opt_i=0
 opt_k=0
 home_dir="."
-device="pngmono"
-mult="0.9"
+device=""
+
 while [ -n "$1" ]; do
 case $1 in
-    -g) device="pnggray" ; shift 1;;
-    -c) device="png16m" ; shift 1;;
-    -i) opt_i=1 ; shift 1;;
-    -h) help;shift 1;;
-    -k) opt_k=1;shift 1;; # variable opt_f is set
-    -d) opt_d=$2;shift 2;; # -d takes an argument -> shift by 2
-    -H) home_dir=$2;shift 2;;
+    -g) device="-depth 8";    shift 1;; #gray
+    -c) device="";            shift 1;; #color
+    -m) device="-depth 1"; shift 1;; #monochrome
+    -h) help;        shift 1;;
+    -i) opt_i=1;     shift 1;;
+    -k) opt_k=1;     shift 1;; 
+    -d) opt_d=$2;    shift 2;; #shift by 2 due to argument
+    -H) home_dir=$2; shift 2;;
     --) break;;
-    -*) echo "error: no such option $1. -h for help";exit 1;;
+    -*) echo "error: no such option $1"; exit 1;;
     *)  break;;
 esac
 done
 
 # input check:
 if [ -z "$1" ] ; then
- error "ERROR: you must specify a file, use -h for help"
- exit 1
+	error "no latex_file specified"
+	exit 1
 fi
 
 #process 'latex2png file.tex' and 'latex2png file' equivalently
 name=`basename "$1" ".tex"`
 dir=`dirname "$1"`
-start_dir=`pwd`
 
-#need to search the current working directory for \input or \include
+#add $home_dir to latex/dvips search path
 cd $home_dir
-TEXINPUTS=`pwd`":"
+TEXINPUTS=`pwd`${TEXINPSEP}
 export TEXINPUTS
-cd $start_dir
 cd $dir
-rm -f $name.png
-rm -f $name.dvi
-$LATEX  --interaction batchmode $1 > /dev/null
+
+$LATEX $name > /dev/null
 
 if [ ! -e "$name.dvi" ] ; then
- 	error "ERROR: latex failed to create $name.dvi from $name.tex"
+ 	echo "error: latex failed to translate $name.tex to $name.dvi"
 	exit 1
 fi
 
-dvips -E -o $name.eps $name.dvi >& /dev/null
+$DVIPS -o $name.tmp.ps $name.dvi >& /dev/null
 
-if [ ! -e "$name.eps" ] ; then
- 	error "ERROR: dvips failed to create $name.eps from $name.dvi"
+if [ ! -e "$name.tmp.ps" ] ; then
+ 	echo "error: dvips failed to translate $name.dvi to $name.tmp.ps"
 	exit 1
 fi
 
-convert -crop 0x0 -density ${opt_d}x${opt_d} $name.eps $name.png
+#helps convert work with eps figures
+$PS2PS $name.tmp.ps $name.ps
+if [ ! -e "$name.ps" ] ; then
+ 	echo "error: ps2ps (Ghostscript) failed to translate $name.tmp.ps from $name.ps"
+ 	exit 1
+fi
+
+$CONVERT ${device} -density ${opt_d}x${opt_d} $name.ps $name.png
 
 if [ ! -e "$name.png" ] ; then
- 	error "ERROR: ImageMagick convert failed to create $name.png from $name.eps"
-	exit 1
+ 	echo "error: convert (ImageMagick) failed to translate $name.ps from $name.png"
+ 	exit 1
 fi
 
 if [ $opt_k -eq 0 ] ; then
 	rm -f $name.dvi
 	rm -f $name.aux
 	rm -f $name.log
-	rm -f $name.eps
+	rm -f $name.ps
+	rm -f $name.tmp.ps
 fi
 
 exit 0
diff --git a/scripts/latex2png_2 b/scripts/latex2png_2
--- a/scripts/latex2png_2
+++ b/scripts/latex2png_2
@@ -1,76 +1,119 @@
 #!/bin/sh
-# This version uses pdflatex
-#              and  pstoimg that comes with latex2html
+# Part of latex2rtf by Scott Prahl (Nov 2002)
 #
+# This version uses latex and dvips
+#              with ghostscript
+#              and  pnmcrop and pnmtopng
+#
+
+DVIPS="dvips -E -R"
+GHOSTSCRIPT="gs -dQUIET -dNOPAUSE -dBATCH -dSAFER"
+LATEX="latex --interaction batchmode"
+PNMCROP="pnmcrop"
+PNMTOPNG="pnmtopng"
+TEXINPSEP=":"
+
 help()
 {
     cat <<HELP
 latex2png -- convert latex file to PNG image
 
-USAGE: latex2png [-d density] [-h] [-k] [-H home dir] latex_file
+USAGE: latex2png [-d density] [-h] [-k] [-c] [-g] [-m] [-H home dir] latex_file
 
-OPTIONS: -d density (where density is in pixels per inch)
-         -h         	this help text
-         -k         	keep intermediate files (for debugging)
-         -H /home/dir	directory to be included in search path
+OPTIONS: 
+         -c color image
+         -g gray image  
+         -m monochrome  (default)
 
-EXAMPLE: latex2png -d 144 -H /usr/home /tmp/eqn  (to create /tmp/eqn.png)
+         -d density     (default 144 dpi)
+         -h help        (default '.')
+         -H /home/dir   directory to be included in search path
+         -i             used to locate baseline of equations
+         -k             keep intermediate files (for debugging)
+
+EXAMPLE: 
+         latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
+         latex2png -H . /tmp/file     #search the cwd for image files
 
 HELP
     exit 0
 }
 
 opt_d=144
+opt_i=0
 opt_k=0
 home_dir="."
+device="b"                      #black & white
+ext="pbm"
+output="pbmraw"
+
 while [ -n "$1" ]; do
 case $1 in
-    -h) help;shift 1;;
-    -k) opt_k=1;shift 1;; # variable opt_f is set
-    -d) opt_d=$2;shift 2;; # -d takes an argument -> shift by 2
-    -H) home_dir=$2;shift 2;;
+    -g) ext="pgm";  output="pgmraw"; shift 1;; #gray
+    -c) ext="ppm";  output="ppmraw";  shift 1;; #color
+    -m) ext="pbm";  output="pbmraw"; shift 1;; #monochrome
+    -h) help;        shift 1;;
+    -i) opt_i=1;     shift 1;;
+    -k) opt_k=1;     shift 1;; 
+    -d) opt_d=$2;    shift 2;; #shift by 2 due to argument
+    -H) home_dir=$2; shift 2;;
     --) break;;
-    -*) echo "error: no such option $1. -h for help";exit 1;;
+    -*) echo "error:no such option $1"; exit 1;;
     *)  break;;
 esac
 done
 
 # input check:
 if [ -z "$1" ] ; then
- error "ERROR: you must specify a file, use -h for help"
+ echo "error: no latex_file specified"
  exit 1
 fi
 
 #process 'latex2png file.tex' and 'latex2png file' equivalently
 name=`basename "$1" ".tex"`
 dir=`dirname "$1"`
-start_dir=`pwd`
 
-#need to search the current working directory for \input or \include
+#add $home_dir to latex/dvips search path
 cd $home_dir
-TEXINPUTS=`pwd`":"
+TEXINPUTS=`pwd`${TEXINPSEP}
 export TEXINPUTS
-cd $start_dir
 cd $dir
-rm -f $name.png
-rm -f $name.pdf
 
-pdflatex  --interaction batchmode $name > /dev/null
+$LATEX $name > /dev/null
 
-if [ ! -e "$name.pdf" ] ; then
- 	error "ERROR: pdflatex failed to create $name.pdf"
-	exit 1
+if [ ! -e "$name.dvi" ] ; then
+    echo "error: latex failed to translate $name.tex to $name.dvi"
+    exit 1
 fi
 
-pstoimg -crop lbtr -density ${opt_d} -type png $name.pdf >& /dev/null
+$DVIPS -o $name.ps $name.dvi >& /dev/null
+
+if [ ! -e "$name.ps" ] ; then
+    echo "error: dvips failed to translate $name.dvi to $name.ps"
+    exit 1
+fi
+
+$GHOSTSCRIPT -sDEVICE=${output} -r${opt_d} -sOutputFile=$name.$ext $name.ps >& /dev/null
+
+if [ ! -e "$name.$ext" ] ; then
+    echo "error: ghostscript failed to translate $name.ps to $name.$ext"
+    exit 1
+fi
+
+$PNMCROP $name.$ext | $PNMTOPNG > $name.png 2> /dev/null
 
 if [ ! -e "$name.png" ] ; then
- 	error "ERROR: pstoimg failed to create $name.png from $name.pdf"
-	exit 1
+    echo "error: pnmcrop or pnmtopng failed to crop and translate $name.$ext to $name.png"
+    exit 1
 fi
 
 if [ $opt_k -eq 0 ] ; then
-	rm -f $name.aux
-	rm -f $name.log
-	rm -f $name.pdf
+    rm -f $name.dvi
+    rm -f $name.aux
+    rm -f $name.log
+    rm -f $name.ps
+    rm -f $name.$ext
 fi
+
+exit 0
+
diff --git a/scripts/latex2png_3 b/scripts/latex2png_3
--- a/scripts/latex2png_3
+++ b/scripts/latex2png_3
@@ -1,90 +1,1 @@
-#!/bin/sh
-# This version uses latex and dvips
-#              with ghostscript
-#              and  pnmcrop and pnmtopng
-#
-help()
-{
-    cat <<HELP
-latex2png -- convert latex file to PNG image
-
-USAGE: latex2png [-d density] [-h] [-k] [-H home dir] latex_file
-
-OPTIONS: -d density (where density is in pixels per inch)
-         -h         	this help text
-         -k         	keep intermediate files (for debugging)
-         -H /home/dir	directory to be included in search path
-
-EXAMPLE: latex2png -d 144 -H /usr/home /tmp/eqn  (to create /tmp/eqn.png)
-
-HELP
-    exit 0
-}
-
-opt_d=144
-opt_k=0
-home_dir="."
-while [ -n "$1" ]; do
-case $1 in
-    -h) help;shift 1;;
-    -k) opt_k=1;shift 1;; # variable opt_f is set
-    -d) opt_d=$2;shift 2;; # -d takes an argument -> shift by 2
-    -H) home_dir=$2;shift 2;;
-    --) break;;
-    -*) echo "error: no such option $1. -h for help";exit 1;;
-    *)  break;;
-esac
-done
-
-# input check:
-if [ -z "$1" ] ; then
- error "ERROR: you must specify a file, use -h for help"
- exit 1
-fi
-
-#process 'latex2png file.tex' and 'latex2png file' equivalently
-name=`basename "$1" ".tex"`
-dir=`dirname "$1"`
-start_dir=`pwd`
-
-#need to search the current working directory for \input or \include
-cd $home_dir
-TEXINPUTS=`pwd`":"
-export TEXINPUTS
-cd $start_dir
-cd $dir
-rm -f $name.png
-rm -f $name.dvi
-
-latex  --interaction batchmode $name > /dev/null
-
-if [ ! -e "$name.dvi" ] ; then
- 	error "ERROR: latex failed to create $name.dvi from $name.tex"
-	exit 1
-fi
-
-dvips -E -o $name.eps $name.dvi >& /dev/null
-
-if [ ! -e "$name.eps" ] ; then
- 	error "ERROR: dvips failed to create $name.eps from $name.dvi"
-	exit 1
-fi
-
-gs -dNOPAUSE -sDEVICE=pbmraw -r${opt_d} -sOutputFile=$name.pbm $name.eps -c quit.ps >& /dev/null
-pnmcrop $name.pbm | pnmtopng > $name.png 2> /dev/null
- 
-if [ ! -e "$name.png" ] ; then
- 	error "ERROR: gs/pnmcrop/pnmtopng failed to create $name.eps from $name.png"
-	exit 1
-fi
-
-if [ $opt_k -eq 0 ] ; then
-	rm -f $name.dvi
-	rm -f $name.aux
-	rm -f $name.log
-	rm -f $name.eps
-	rm -f $name.pbm
-fi
-
-exit 0
-
+#!/bin/sh# Part of latex2rtf by B. Horeni (Nov 2002)#         hacked so it does not work by Scott Prahl## This version uses latex and dvips#              with ghostscript#              and  epsbb and png2png## for os2#   rename latex2png to latex2png.cmd #   insert first line "extproc sh" (without ")#   use these definitions#   GS="gsos2"#   TEXINPSEP=";"#   LATEX="tex -progname=cslatex -default-translate-file=cp852-cs"#GHOSTSCRIPT="gs -dQUIET -dNOPAUSE -dBATCH -dSAFER"LATEX="latex --interaction batchmode"DVIPS="dvips -E -R"TEXINPSEP=":"help(){    cat <<HELPlatex2png -- convert latex file to PNG imageUSAGE: latex2png [-d density] [-h] [-k] [-c] [-g] [-m] [-H home dir] latex_fileOPTIONS:          -c color image         -g gray image           -m monochrome  (default)         -d density     (default 144 dpi)         -h help        (default '.')         -H /home/dir   directory to be included in search path         -i             used to locate baseline of equations         -k             keep intermediate files (for debugging)EXAMPLE:          latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi         latex2png -H . /tmp/file     #search the cwd for image filesHELP    exit 0}opt_d=144opt_k=0opt_i="off"home_dir="."device="pngmono"while [ -n "$1" ]; docase $1 in    -g) device="pnggray" ; shift 1;; #gray    -c) device="png16m" ;  shift 1;; #color    -m) device="pngmono";  shift 1;; #monochrome    -h) help;shift 1;;    -i) opt_i="on" ; shift 1;;    -k) opt_k=1;shift 1;;    -d) opt_d=$2;shift 2;; # -d takes an argument -> shift by 2    -H) home_dir=$2;shift 2;;    --) break;;    -*) echo "error: no such option $1"; exit 1;;    *)  break;;esacdone# input check:if [ -z "$1" ] ; then echo "error: no latex_file specified" exit 1fi#process 'latex2png file.tex' and 'latex2png file' equivalentlyname=`basename "$1" ".tex"`dir=`dirname "$1"`#add $home_dir to latex/dvips search pathcd $home_dirTEXINPUTS=`pwd`${TEXINPSEP}export TEXINPUTScd $dir$LATEX $name > /dev/nullif [ ! -e "$name.dvi" ] ; then    echo "error: latex failed to convert $name.tex from $name.dvi"    exit 1fi$DVIPS -o $name.eps $name.dvi > /dev/null 2>&1if [ ! -e "$name.eps" ] ; then    echo "error: dvips failed to create $name.dvi from $name.eps"    exit 1fiGSOPT=`epsbb -r${opt_d} -l $name.eps` $GHOSTSCRIPT -sDEVICE=${device} -sOutputFile=$name.map ${GSOPT} 2> /dev/nullif [ $opt_i -eq 1 ] ; then        png2png -b -Y $mult $name.map $name.png $name.off   # 2> /dev/nullelse        png2png $name.map $name.png    # 2> /dev/null       fiif [ ! -e "$name.png" ] ; then    echo "error: ghostscript or png2png failed to create $name.eps from $name.png"    exit 1fiif [ $opt_k -eq 0 ] ; then    rm -f $pathname.dvi    rm -f $pathname.aux    rm -f $pathname.log    rm -f $pathname.eps    rm -f $pathname.mapfiexit 0
diff --git a/scripts/latex2png_5 b/scripts/latex2png_5
--- a/scripts/latex2png_5
+++ b/scripts/latex2png_5
@@ -1,13 +1,15 @@
 #!/bin/sh
 # Part of latex2rtf by Scott Prahl (Nov 2002)
 #
-# This version uses pdflatex and convert that comes with ImageMagick
+# This version uses pdflatex
+#              and  pstoimg that comes with latex2html
 #
 # this version does not work with included eps graphics unless pdflatex has
 # supports the eps graphic format.  Works fine for for including equations.
+#
 
 PDFLATEX="pdflatex --interaction batchmode"
-CONVERT="convert -crop 0x0"
+PSTOIMG="pstoimg"
 TEXINPSEP=":"
 
 help()
@@ -40,27 +42,27 @@ opt_d=144
 opt_i=0
 opt_k=0
 home_dir="."
-device="-monochrome"
+device="1"                      #black & white
 
 while [ -n "$1" ]; do
 case $1 in
-    -g) device="-depth 8";    shift 1;; #gray
-    -c) device="";            shift 1;; #color
-    -m) device="-monochrome"; shift 1;; #monochrome
+    -g) device="8";  shift 1;; #gray
+    -c) device="24"; shift 1;; #color
+    -m) device="1";  shift 1;; #monochrome
     -h) help;        shift 1;;
     -i) opt_i=1;     shift 1;;
     -k) opt_k=1;     shift 1;; 
     -d) opt_d=$2;    shift 2;; #shift by 2 due to argument
     -H) home_dir=$2; shift 2;;
     --) break;;
-    -*) echo "error: no such option $1"; exit 1;;
+    -*) echo "error:no such option $1"; exit 1;;
     *)  break;;
 esac
 done
 
 # input check:
 if [ -z "$1" ] ; then
- echo "error: no latex_file specified"
+ echo "no latex_file specified"
  exit 1
 fi
 
@@ -68,7 +70,7 @@ fi
 name=`basename "$1" ".tex"`
 dir=`dirname "$1"`
 
-#add $home_dir to pdflatex search path
+#need to search the current working directory for \input or \include
 cd $home_dir
 TEXINPUTS=`pwd`${TEXINPSEP}
 export TEXINPUTS
@@ -81,10 +83,10 @@ if [ ! -e "$name.pdf" ] ; then
     exit 1
 fi
 
-$CONVERT ${device} -density ${opt_d}x${opt_d} $name.pdf $name.png
+$PSTOIMG -crop lbtr -color ${device} -density ${opt_d} -type png $name.pdf >& /dev/null
 
 if [ ! -e "$name.png" ] ; then
-    echo "error: convert (ImageMagick) failed to translate $name.pdf to $name.png"
+    echo "error: pstoimg (from latex2html) failed to translate $name.pdf to $name.png"
     exit 1
 fi
 
@@ -93,4 +95,3 @@ if [ $opt_k -eq 0 ] ; then
     rm -f $name.log
     rm -f $name.pdf
 fi
-exit 0
