WH: modified latex2png script to that it also tries xelatex
git-svn-id: https://latex2rtf.svn.sourceforge.net/svnroot/latex2rtf/trunk@1222 e562ef82-0334-0410-8083-dbe22b1e9a75

diff --git a/scripts/latex2png b/scripts/latex2png
--- a/scripts/latex2png
+++ b/scripts/latex2png
@@ -23,6 +23,7 @@
 DVIPS="dvips -q -l 1 -E -R"
 LATEX="latex --interaction batchmode --output-format dvi"
 PDFLATEX="latex --interaction batchmode --output-format pdf"
+XELATEX="xelatex -interaction=batchmode"
 CONVERT="convert"
 PDF2EPS="eps2eps"
 GREP="grep"
@@ -31,8 +32,8 @@ SED="sed"
 # !!!!!!!!!!!!!!!! Note !!!!!!!!!!!!!!
 # Under MS Windows, although this script runs under bash shell,
 # LaTeX is run in the Windows environment and thus needs the ";" as separator.
-TEXINPSEP=":" #Unix
-#TEXINPSEP=";"  #MS Windows
+#TEXINPSEP=":" #Unix
+TEXINPSEP=";"  #MS Windows
 VERSION="1.10"
 
 help()
@@ -148,8 +149,18 @@ if [ $ext = "tex" ] ; then
              exit 1
           fi
        else
-          echo "latex2png: error: latex failed to translate $name.tex to $name.pdf"
-          exit 1
+          echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
+          $XELATEX $name > /dev/null
+          if [ -e "$name.pdf" ] ; then
+             $PDF2EPS $name.pdf $name.eps
+             if [ ! -e "$name.eps" ] ; then
+                echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
+                exit 1
+             fi
+          else
+             echo "latex2png: error: xelatex failed to translate $name.tex to $name.pdf"
+             exit 1
+          fi
        fi
     fi
  
@@ -163,9 +174,30 @@ if [ $ext = "tex" ] ; then
            # now create an eps without the adjustment stuff
            $SED -e "s/\^I_g//" $name.tex >$name.tmp
            rm $name.tex
+           rm $name.pdf
+           rm $name.eps
            mv $name.tmp $name.tex
            $LATEX $name > /dev/null
-           $DVIPS -o $name.eps $name.dvi
+           if [ -e "$name.dvi" ] ; then
+              $DVIPS -o $name.eps $name.dvi
+           else
+              echo "latex2png: latex failed to translate $name.tex w/o adj to $name.dvi, trying pdflatex"
+              $PDFLATEX $name > /dev/null
+              if [ ! -e "$name.pdf" ] ; then
+                 echo "latex2png: pdflatex failed to translate $name.tex w/o adj to $name.pdf, trying xelatex"
+                 $XELATEX $name > /dev/null
+                 if [ ! -e "$name.pdf" ] ; then
+                    echo "latex2png: error: xelatex failed to translate $name.tex w/o adj to $name.pdf"
+                    exit 1
+                 fi
+              fi
+              $PDF2EPS $name.pdf $name.eps
+           fi
+           if [ ! -e "$name.eps" ] ; then
+              echo "latex2png: error: failed to translate $name.tex to $name.eps"
+              exit 1
+           fi
+
            # extract the BoundingBox of the eps without adjustment stuff
            bbb=`${GREP} -C 0 %%BoundingBox: $name.eps`
            llyfin=$(echo $bbb | $AWK -F" " '{print $3}' )
@@ -183,7 +215,7 @@ if [ $ext = "tex" ] ; then
            fi
         fi
         if [ $opt_k -eq 0 ] ; then
-            rm -f $name.dvi $name.aux $name.log
+            rm -f $name.dvi $name.aux $name.log $name.out
         fi
         exit 0
     fi
