Merge upstream changes (tikz support, and bug fixes).

diff --git a/scripts/latex2png b/scripts/latex2png
--- a/scripts/latex2png
+++ b/scripts/latex2png
@@ -32,9 +32,9 @@ SED="sed"
 # !!!!!!!!!!!!!!!! Note !!!!!!!!!!!!!!
 # Under MS Windows, although this script runs under bash shell,
 # LaTeX is run in the Windows environment and thus needs the ";" as separator.
-TEXINPSEP=":" #Unix
-#TEXINPSEP=";"  #MS Windows
-VERSION="1.30"
+#TEXINPSEP=":" #Unix
+TEXINPSEP=";"  #MS Windows
+VERSION="1.40"
 
 help()
 {
@@ -136,21 +136,19 @@ if [ $ext = "tex" ] ; then
     rm -f $name.eps
     rm -f $name.png
 
-    $LATEX $name > /dev/null
-    
-    if [ -e "$name.dvi" ] ; then
-       $DVIPS -o $name.eps $name.dvi
+
+    $PDFLATEX $name > /dev/null
+    if [ -e "$name.pdf" ] ; then
+       $PDF2EPS $name.pdf $name.eps
        if [ ! -e "$name.eps" ] ; then
-         if [ $opt_k -eq 1 ] ; then
-            echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
-         fi
-         exit 1
+          echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
+          exit 1
        fi
     else
        if [ $opt_k -eq 1 ] ; then
-          echo "latex2png: latex failed to translate $name.tex to $name.dvi, trying pdflatex"
+          echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
        fi
-       $PDFLATEX $name > /dev/null
+       $XELATEX $name > /dev/null
        if [ -e "$name.pdf" ] ; then
           $PDF2EPS $name.pdf $name.eps
           if [ ! -e "$name.eps" ] ; then
@@ -159,17 +157,20 @@ if [ $ext = "tex" ] ; then
           fi
        else
           if [ $opt_k -eq 1 ] ; then
-             echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
+             echo "latex2png: xelatex failed to translate $name.tex to $name.dvi, trying latex"
           fi
-          $XELATEX $name > /dev/null
-          if [ -e "$name.pdf" ] ; then
-             $PDF2EPS $name.pdf $name.eps
+          $LATEX $name > /dev/null
+          if [ -e "$name.dvi" ] ; then
+             $DVIPS -o $name.eps $name.dvi
              if [ ! -e "$name.eps" ] ; then
-                echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
-                exit 1
+               if [ $opt_k -eq 1 ] ; then
+                  echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
+                  exit 1
+               fi
+               exit 1
              fi
           else
-             echo "latex2png: error: xelatex failed to translate $name.tex to $name.pdf"
+             echo "latex2png: error: pdflatex, xelatex and latex all failed to translate $name.tex"
              exit 1
           fi
        fi
@@ -188,25 +189,29 @@ if [ $ext = "tex" ] ; then
            rm -f $name.pdf
            rm $name.eps
            mv $name.tmp $name.tex
-           $LATEX $name > /dev/null
-           if [ -e "$name.dvi" ] ; then
-              $DVIPS -o $name.eps $name.dvi
+
+           $PDFLATEX $name > /dev/null
+           if [ -e "$name.pdf" ] ; then
+              $PDF2EPS $name.pdf $name.eps
            else
               if [ $opt_k -eq 1 ] ; then
-                 echo "latex2png: latex failed to translate $name.tex w/o adj to $name.dvi, trying pdflatex"
+                 echo "latex2png: pdflatex failed to translate $name.tex w/o adj to $name.pdf, trying xelatex"
               fi
-              $PDFLATEX $name > /dev/null
-              if [ ! -e "$name.pdf" ] ; then
+              $XELATEX $name > /dev/null
+              if [ -e "$name.pdf" ] ; then
+                 $PDF2EPS $name.pdf $name.eps
+              else
                  if [ $opt_k -eq 1 ] ; then
-                    echo "latex2png: pdflatex failed to translate $name.tex w/o adj to $name.pdf, trying xelatex"
+                    echo "latex2png: error: xelatex failed to translate $name.tex w/o adj to $name.pdf, trying latex"
                  fi
-                 $XELATEX $name > /dev/null
-                 if [ ! -e "$name.pdf" ] ; then
-                    echo "latex2png: error: xelatex failed to translate $name.tex w/o adj to $name.pdf"
+                 $LATEX $name > /dev/null
+                 if [ -e "$name.dvi" ] ; then
+                    $DVIPS -o $name.eps $name.dvi
+                 else
+                    echo "latex2png: pdflatex, xelatex and latex all failed to translate $name.tex w/o adj"
                     exit 1
                  fi
               fi
-              $PDF2EPS $name.pdf $name.eps
            fi
            if [ ! -e "$name.eps" ] ; then
               echo "latex2png: error: failed to translate $name.tex to $name.eps"
@@ -230,11 +235,10 @@ if [ $ext = "tex" ] ; then
            fi
         fi
         if [ $opt_k -eq 0 ] ; then
-            rm -f $name.dvi $name.aux $name.log $name.out
+            rm -f $name.pdf $name.dvi $name.aux $name.log $name.out
         fi
         exit 0
     fi
-    
 fi
 
 # WH: added "-type TrueColor" to ensure compatibility with older versions of Word and with IrfanView
